<?php
class EssentialVerbs {

   public static function getVerbs()
   {
       return self::$essential_verbs;
   }

   private static $essential_verbs = array("arbeiten",
         "bekommen",
         "bleiben",
         "brauchen",
         "bringen",
         "denken",
         "essen",
         "fahren",
         "finden",
         "fragen",
         "geben",
         "gehen",
         "gehören",
         "glauben",
         "haben",
         "halten",
         "heißen",
         "helfen",
         "hören",
         "kaufen",
         "kennen",
         "kommen",
         "können",
         "lassen",
         "laufen",
         "leben",
         "legen",
         "liegen",
         "machen",
         "mögen",
         "müssen",
         "nehmen",
         "sagen",
         "schlafen",
         "schlagen",
         "schreiben",
         "sehen",
         "sein",
         "sitzen",
         "sollen",
         "spielen",
         "sprechen",
         "stehen",
         "stellen",
         "sterben",
         "tragen",
         "treffen",
         "tun",
         "warten",
         "werden",
         "werfen",
         "wissen",
         "wohnen",
         "wollen",
         "ziehen");
}
